/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./src/components/ui/alert/AlertDescription.vue')['default']
    AlertDialog: typeof import('./src/components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    AlertTitle: typeof import('./src/components/ui/alert/AlertTitle.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sonner: typeof import('./src/components/ui/sonner/Sonner.vue')['default']
  }
}
